package adapter

import (
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

// AgentInventory is the read-only local inventory shared by the CLI and
// diagnostics. Unsupported entries intentionally have no resource kinds or
// capabilities and can never become writable targets.
type AgentInventory struct {
	ID            string   `json:"id"`
	Status        string   `json:"status"`
	Availability  string   `json:"availability"`
	ResourceKinds []string `json:"resourceKinds"`
	Capabilities  []string `json:"capabilities"`
}

// Inventory returns supported adapters and agent-shaped unsupported locations
// discovered under home and, when supplied, project. It only reads local
// directory metadata and executable availability.
func Inventory(home, project string) ([]AgentInventory, error) {
	items := make([]AgentInventory, 0, len(Supported()))
	for _, a := range Supported() {
		availability, err := availability(a, home, project)
		if err != nil {
			return nil, err
		}
		item := AgentInventory{
			ID:            string(a.Target()),
			Status:        "supported",
			Availability:  availability,
			ResourceKinds: []string{},
			Capabilities:  []string{},
		}
		for _, kind := range a.ResourceKinds() {
			item.ResourceKinds = append(item.ResourceKinds, string(kind))
			for _, capability := range a.Capabilities(kind) {
				item.Capabilities = append(item.Capabilities, string(capability))
			}
		}
		items = append(items, item)
	}
	unsupported, err := unsupportedInventory(home, project)
	if err != nil {
		return nil, err
	}
	return append(items, unsupported...), nil
}

// SupportedProjectRoots returns the top-level project directories reserved by
// registered adapters, plus manager metadata roots. It is the shared policy
// for deciding whether a dot-directory is a known agent location.
func SupportedProjectRoots(project string) map[string]bool {
	known := map[string]bool{".agents": true, ".git": true, ".skill-manager": true}
	for _, a := range Supported() {
		root := filepath.Dir(a.ProjectSkillPath(project, "placeholder"))
		rel, err := filepath.Rel(project, root)
		if err != nil {
			continue
		}
		parts := strings.Split(rel, string(filepath.Separator))
		if len(parts) > 0 && parts[0] != "" && parts[0] != "." && !strings.HasPrefix(parts[0], "..") {
			known[parts[0]] = true
		}
	}
	return known
}

// MatchProjectSkillPath identifies a single safe skill placement generated by
// a registered adapter. The candidate must be exactly one valid identifier
// below an adapter's project skills directory.
func MatchProjectSkillPath(project, candidate string) (Adapter, string, bool) {
	project, err := filepath.Abs(project)
	if err != nil {
		return nil, "", false
	}
	candidate, err = filepath.Abs(candidate)
	if err != nil {
		return nil, "", false
	}
	for _, a := range Supported() {
		root := filepath.Dir(a.ProjectSkillPath(project, "placeholder"))
		rel, err := filepath.Rel(root, candidate)
		if err != nil || ValidateIdentifier(rel) != nil {
			continue
		}
		if err := ValidateProjectPlacement(a.Target(), project, candidate, rel); err != nil {
			continue
		}
		return a, rel, true
	}
	return nil, "", false
}

func availability(a Adapter, home, project string) (string, error) {
	if project != "" {
		absolute, err := filepath.Abs(project)
		if err == nil {
			detection, err := a.Detect(DetectionRequest{Project: absolute})
			if err == nil && detection.Configured {
				return "configured", nil
			}
		}
	}
	if _, err := exec.LookPath(agentCommand(a.Target())); err == nil {
		return "detected", nil
	}
	configRoot := filepath.Dir(filepath.Dir(a.GlobalSkillPath(home, "placeholder")))
	info, err := os.Stat(configRoot)
	if err == nil && info.IsDir() {
		return "configured", nil
	}
	return "unavailable", nil
}

func unsupportedInventory(home, project string) ([]AgentInventory, error) {
	roots := []string{home}
	if project != "" {
		absolute, err := filepath.Abs(project)
		if err != nil {
			return nil, err
		}
		roots = append(roots, absolute)
	}
	items := make([]AgentInventory, 0)
	seen := make(map[string]bool)
	for _, root := range roots {
		locations, err := UnsupportedAgentRoots(root)
		if err != nil {
			return nil, err
		}
		for _, location := range locations {
			id := strings.TrimPrefix(filepath.Base(location), ".")
			if seen[id] {
				continue
			}
			seen[id] = true
			items = append(items, AgentInventory{ID: id, Status: "unsupported", Availability: "unsupported", ResourceKinds: []string{}, Capabilities: []string{}})
		}
	}
	sort.Slice(items, func(i, j int) bool { return items[i].ID < items[j].ID })
	return items, nil
}

// UnsupportedAgentRoots returns project or home agent locations that look
// like an unregistered adapter. Both the agent directory and its skills child
// must be real directories; symlinks and regular files are never discovered.
func UnsupportedAgentRoots(root string) ([]string, error) {
	known := SupportedProjectRoots(root)
	entries, err := os.ReadDir(root)
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	locations := make([]string, 0)
	for _, entry := range entries {
		name := entry.Name()
		// Cc Switch stores its own skill references under this directory, but it
		// is a tool/configuration manager rather than an agent runtime.
		if len(name) < 2 || name[0] != '.' || known[name] || name == ".cc-switch" {
			continue
		}
		location := filepath.Join(root, name)
		info, err := os.Lstat(location)
		if err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return nil, err
		}
		if info.Mode()&os.ModeSymlink != 0 || !info.IsDir() {
			continue
		}
		skillsRoot := filepath.Join(location, "skills")
		info, err = os.Lstat(skillsRoot)
		if err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return nil, err
		}
		if info.Mode()&os.ModeSymlink != 0 || !info.IsDir() {
			continue
		}
		locations = append(locations, location)
	}
	sort.Strings(locations)
	return locations, nil
}

func agentCommand(target Target) string {
	if target == ClaudeCode {
		return "claude"
	}
	return string(target)
}
